cache:
  mount:
    - /drone/repository

publish:
  docker:
    repo: monitor/prometheus
    file: Dockerfile
    when:
      branch: master
      event: [push, pull_request]

  docker:
    repo: monitor/prometheus
    file: Dockerfile
    tag:
      - "$$TAG"
    when:
      event: tag
