cache:
  mount:
    - /drone/repository

publish:
  docker:
    repo: monitor/prometheus
    file: Dockerfile
    when:
      branch: master
      event: [push, pull_request]

  docker:
    repo: monitor/prometheus
    file: Dockerfile
    tag:
      - "$$TAG"
    when:
      event: tag

downstream:
    repositories:
      - monitor/monitor-deploy
    token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0ZXh0IjoieWFuZ3RhbyIsInR5cGUiOiJ1c2VyIn0.okkR6oWlPPplpsAsTPPI8RqLzJMkc08EXlOtkVN0b4k
    fork: true
    when:
      repo: monitor/prometheus
      event: [tag]
      success: true