prometheus:
    image: "docker.finogeeks.club/mesons/prometheus"
    ports:
        - "9999:9090"
alertmanager:
    image: "docker.finogeeks.club/base/alertmanager:v0.6.2"
    ports:
        - "9093:9093"
grafana:
    image: "docker.finogeeks.club/base/grafana"
    ports:
        - "3000:3000"
    environment:
        GF_SECURITY_ADMIN_PASSWORD: abcd@1234
        GF_SERVER_ROOT_URL: http://localhost
    volumes:
        - "/var/monitor/grafana:/var/lib/grafana"
