version: '2'
services:
    cAdvisor:
        image: docker.finogeeks.club/monitor/cadvisor
        volumes:
          - /:/rootfs:ro
          - /var/run:/var/run:rw
          - /sys:/sys:ro
          - /var/lib/docker/:/var/lib/docker:ro
    node-exporter:
        image: docker.finogeeks.club/monitor/node-exporter
        privileged: true
        pid: host
        volumes:
          - /proc:/host/proc:ro
          - /sys:/host/sys:ro
          - /:/rootfs:ro
    prometheus:
        image: "docker.finogeeks.club/monitor/prometheus"
        ports:
          - 9999:9090
    alertmanager:
        image: "docker.finogeeks.club/monitor/alertmanager"
    alert-webhook:
        image: "docker.finogeeks.club/monitor/alert-webhook"
        environment:
            HOMESERVER_URL: https://chat.finogeeks.club
            DEPLOY_ENV: test
