version: '2'
services:
    cAdvisor:
        image: docker.finogeeks.club/monitor/cadvisor
        pid: host
        volumes:
          - /:/rootfs:ro
          - /var/run:/var/run:rw
          - /sys:/sys:ro
          - /var/lib/docker/:/var/lib/docker:ro
    node-exporter:
        image: docker.finogeeks.club/monitor/node-exporter
        privileged: true
        pid: host
#        volumes:
#          - /proc:/host/proc:ro
#          - /sys:/host/sys:ro
#          - /:/rootfs:ro
    api-prober:
        image: docker.finogeeks.club/monitor/api-prober
        environment:
            env: finogeeks
            ENABLE_MONITOR: 'true'
    platform-api:
        image: "docker.finogeeks.club/finochat/platform-api"
        environment:
            ENABLE_MONITOR: 'true'
        ports:
          - 13000:3000
    rcs-server:
        image: docker.finogeeks.club/finochat/rcs-server
        environment:
            ENABLE_MONITOR: 'true'
            mongo.db: rcs
            mongo.cluster.domain: mongo
        ports:
          - 28080:8080
    mongo:
        image: docker.finogeeks.club/base/mongo:3.4

    prometheus:
        image: "docker.finogeeks.club/monitor/prometheus"
        environment:
          CONFIG_FILE: prometheus.yml
        ports:
          - 9999:9090
    alertmanager:
        image: "docker.finogeeks.club/monitor/alertmanager"
    alert-webhook:
        image: "docker.finogeeks.club/monitor/alert-webhook"
        environment:
            HOMESERVER_URL: https://chat.finogeeks.club
            USERID: "@alarm-bot:finogeeks.club"
            PASSWD: "fino@@123321"
            DEPLOY_ENV: test
    gateway:
        image: "docker.finogeeks.club/finochat/gateway"
        privileged: true
        command: kong start --run-migrations
        ports:
          - 8000:8000
        environment:
          - KONG_DATABASE=postgres
          - KONG_PG_HOST=10.135.179.195
          - KONG_PG_PASSWORD=123123
