version: '2'
services:
    cAdvisor:
        image: docker.finogeeks.club/monitor/cadvisor
        volumes:
          - /:/rootfs:ro
          - /var/run:/var/run:rw
          - /sys:/sys:ro
          - /var/lib/docker/:/var/lib/docker:ro
        command: 
          - "--port=8080"
          - "--allow_dynamic_housekeeping=false"
        ports:
          - "8080:8080"
    netdata:
        image: docker.finogeeks.club/monitor/netdata
        privileged: true
        pid: host
        volumes:
          - /proc:/host/proc:ro
          - /sys:/host/sys:ro
        ports:
          - "19999:19999"
    node-exporter:
        image: docker.finogeeks.club/monitor/node-exporter
        privileged: true
        pid: host
        volumes:
          - /proc:/host/proc:ro
          - /sys:/host/sys:ro
          - /:/rootfs:ro
        command:
          - '-collector.procfs=/host/proc'
          - '-collector.sysfs=/host/sys'
          - '-collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
    prometheus:
        image: "docker.finogeeks.club/monitor/prometheus"
        ports:
            - "9999:9090"
        extra_hosts:
            - "chat.finogeeks.club:10.135.138.50"
            - "chat.finogeeks.com:10.135.141.191"
            - "helper.bot.finogeeks.club:10.135.180.220"
            - "helper.bot.finogeeks.com:10.135.180.120"
            - "openacc.bot.finogeeks.club:10.135.180.220"
            - "openacc.bot.finogeeks.com:10.135.180.120"
    alertmanager:
        image: "docker.finogeeks.club/monitor/alertmanager"
        ports:
            - "9093:9093"
    alert-webhook:
        image: "docker.finogeeks.club/monitor/alert-webhook"
        environment:
            HOMESERVER_URL: http://10.135.138.50:8008
            DEPLOY_ENV: test
    openldap-exporter:
        image: "docker.finogeeks.club/monitor/openldap_exporter"
        environment:
            LDAP_ADDR: tcp:host=10.135.129.123:port=389
    rancher-exporter:
        image: docker.finogeeks.club/monitor/rancher-exporter:v0.22.52
        environment:
            CATTLE_ACCESS_KEY: "D630F4BD568595DF13A6"
            CATTLE_SECRET_KEY: "EG4N8Bs5zqrSZGbPSLT9qtm7NiWUENiJF4X13bQd"
            CATTLE_URL: "http://10.135.178.5:8080/v2-beta"
            HIDE_SYS: "true"
    statsd-exporter:
        image: "docker.finogeeks.club/monitor/statsd-exporter"
        ports:
            - "9102:9102"
            - "9125:9125/udp"
    api-prober:
        image: "docker.finogeeks.club/monitor/api-prober"
        environment:
            ENABLE_MONITOR: 'true'
