version: '2'
services:
    prometheus:
        image: "docker.finogeeks.club/monitor/prometheus"
        ports:
            - "9999:9090"
    alertmanager:
        image: "docker.finogeeks.club/monitor/alertmanager"
        ports:
            - "9093:9093"
    alert-webhook:
        image: "docker.finogeeks.club/monitor/alert-webhook"
        environment:
            HOMESERVER_URL: http://10.135.129.123:8008
    openldap-exporter:
        image: "docker.finogeeks.club/monitor/openldap_exporter"
        environment:
            LDAP_ADDR: tcp:host=10.135.129.123:port=389
    grafana:
        image: "docker.finogeeks.club/monitor/grafana"
        ports:
            - "3000:3000"
        environment:
            GF_SECURITY_ADMIN_PASSWORD: abcd@1234
            GF_SERVER_ROOT_URL: http://localhost
        volumes:
            - "/var/monitor/grafana:/var/lib/grafana"
