# my global config
global:
  scrape_interval:     30s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 30s # Evaluate rules every 15 seconds. The default is every 1 minute.
#  scrape_timeout:       5s # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'codelab-monitor'

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
    - "/prometheus/rules/homeserver.rules.yml"
    - "/prometheus/rules/docker_host.rules.yml"
    - "/prometheus/rules/container.rules.yml"
    - "/prometheus/rules/service_status.rules.yml"
    - "/prometheus/rules/api_prober.rules.yml"
    - "/prometheus/rules/nodejs_express.rules.yml"
    - "/prometheus/rules/kotlin_vertx.rules.yml"

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'homeserver'
    metrics_path: "/_synapse/metrics"
    static_configs:
      - targets: ['10.135.138.50:9092']

#  - job_name: 'openldap'
#    static_configs:
#      - targets: ['openldap-exporter:8080']
#        labels:
#          domain: 'finogeeks.club'

  - job_name: 'container'
    scrape_interval: 1m
    dns_sd_configs:
    - names:
      - cAdvisor
      type: 'A'
      port: 18080

  - job_name: 'docker_host'
    scrape_interval: 1m
    dns_sd_configs:
    - names:
      - node-exporter
      type: 'A'
      port: 9100

  - job_name: 'api-prober'
    scrape_interval: 1m
    static_configs:
      - targets: ['api-prober:9092']

  - job_name: 'platform-api'
    scrape_interval: 1m
    static_configs:
      - targets: ['platform-api:9092']

  - job_name: 'rcs-server'
    scrape_interval: 1m
    static_configs:
      - targets: ['rcs-server:9092']
